apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  labels:
    name: webapp-config
  namespace: skywalking
data:
  webapp: |-
    server:
      port: 8080
    collector:
      path: /graphql
      ribbon:
        ReadTimeout: 10000
        listOfServers: localhost:10800
    security:
      user:
        admin:
          password: admin
