---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: elasticsearch
    labels:
      app: elasticsearch
    namespace: skywalking
  spec:
    serviceName: elasticsearch
    selector:
      matchLabels:
        app: elasticsearch
    replicas: 1
    template:
      metadata:
        labels:
          app: elasticsearch
      spec:
        containers:
          - name: elasticsearch
            image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
            imagePullPolicy: Always
            securityContext:
              runAsUser: 1000
              allowPrivilegeEscalation: false
            ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: tcp
            env:
              - name: cluster.name
                value: skywalkingdata
              - name: ES_JAVA_OPTS
                value: "-Xms256m -Xmx256m"
              - name: xpack.security.enabled
                value: "false"
              - name: http.host
                value: "0.0.0.0"
              - name: discovery.type
                value: "single-node"
            volumeMounts:
              - name: elkdata
                mountPath: /data
            readinessProbe:
              exec:
                command:
                - curl
                - --fail
                - --silent
                - --output
                - /dev/null
                - --user
                - elastic:changeme
                - localhost:9200
              initialDelaySeconds: 5
              periodSeconds: 5
              timeoutSeconds: 4
        volumes:
          - name: elkdata
            emptyDir: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: elasticsearch
    labels:
      app: skywalking
    namespace: skywalking
  spec:
    clusterIP: None
    selector:
      app: elasticsearch
    ports:
    - port: 9200
      name: elasticsearch
    - port: 9300
      name: transport
